name: MLflow CI Training

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ""
          use-mamba: true

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn pandas seaborn matplotlib numpy

      - name: Run MLflow Project (NO conda activate error)
        run: |
          cd MLProject
          mlflow run . -P data_path=katalog-gempa_preprocessing.csv --env-manager=local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts
          path: MLProject/mlruns/

      - name: Get Latest MLflow Run ID
        id: get_run
        run: |
          LAST_RUN=$(ls -td MLProject/mlruns/0/* | head -n 1)
          echo "run_path=$LAST_RUN" >> $GITHUB_ENV
          echo "Latest run path: $LAST_RUN"

      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            -m $run_path/artifacts/model \
            -n sml-naila:latest

      - name: Login & Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag sml-naila:latest ${{ secrets.DOCKER_USERNAME }}/sml-naila:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sml-naila:latest
