name: MLflow CI Training

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ""
          use-mamba: true

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn pandas seaborn matplotlib numpy docker

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run . -P data_path=katalog-gempa_preprocessing.csv --env-manager=local

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
          mlflow models build-docker \
            -m mlruns/0/*/artifacts/model \
            -n sml-naila:latest

      - name: Login & Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag sml-naila:latest ${{ secrets.DOCKER_USERNAME }}/sml-naila:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sml-naila:latest

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts
          path: MLProject/mlruns
