name: MLflow CI Training

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          python-version: "3.10"
          auto-update-conda: true

      - name: Run MLflow Project (NO conda activate error)
        run: |
          cd MLProject
          mlflow run . -P data_path=dataset_preprocessing.csv --env-manager=local

      - name: Upload MLflow Artifacts (Skilled)
        uses: actions/upload-artifact@v3
        with:
          name: model_artifacts
          path: MLProject/mlruns
