name: MLflow CI Training Advanced

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ""
          use-mamba: true

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn pandas seaborn matplotlib numpy

      - name: Run MLflow Project (training)
        run: |
          # Perintah ini akan otomatis membuat Run ID
          mlflow run MLProject -P data_path=katalog-gempa_preprocessing.csv --env-manager=local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts
          path: |
            **/mlruns
            !**/mlruns/**/tags

      - name: Get Latest MLflow Model Path
        id: get_model
        run: |
          # Cari file 'MLmodel' di seluruh direktori kerja saat ini
          # Urutkan berdasarkan waktu (terbaru di atas) dan ambil 1
          echo "Mencari lokasi model..."
          MODEL_CONF=$(find $(pwd) -name "MLmodel" -print0 | xargs -0 ls -1t | head -n 1)

          if [ -z "$MODEL_CONF" ]; then
            echo "::error::Model tidak ditemukan! Pastikan modelling.py berjalan sukses."
            # Debugging: List file tree jika gagal
            find . -maxdepth 4
            exit 1
          fi

          # Ambil folder parent dari file MLmodel (folder ini yang berisi conda.yaml & model.pkl)
          MODEL_DIR=$(dirname "$MODEL_CONF")
          
          echo "Model ditemukan di: $MODEL_DIR"
          echo "model_path=$MODEL_DIR" >> $GITHUB_OUTPUT

      - name: Enable Docker
        run: |
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image Using MLflow
        run: |
          # Menggunakan path dari step sebelumnya
          mlflow models build-docker \
            -m "${{ steps.get_model.outputs.model_path }}" \
            -n gempa-model

      - name: List Docker Images
        run: docker images

      - name: Tag Docker Image Correctly
        run: |
          docker tag gempa-model ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
