name: MLflow CI Training Advanced

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MLflow and dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Training Script
        working-directory: MLProject
        run: python modelling.py

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns
          if-no-files-found: error

      - name: DEBUG MLflow Folder
        run: |
          echo "===== MLProject/mlruns ====="
          ls -R MLProject/mlruns

      - name: Get Latest MLflow Model Path
        id: get_model
        run: |
          model_path=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort | tail -n 1)
          echo "model_path=$model_path" >> $GITHUB_OUTPUT
          echo "Latest model path: $model_path"

      - name: Enable Docker
        run: |
          sudo systemctl start docker
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image from MLflow Model
        run: |
          mlflow models build-docker \
          -m "${{ steps.get_model.outputs.model_path }}" \
          -t gempa-model

      - name: Tag Docker Image
        run: |
          docker tag gempa-model:latest ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
