name: MLflow CI Training (Advance Level)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MLflow and dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Training Script
        working-directory: MLProject
        run: python modelling.py

      - name: DEBUG mlruns folder
        run: |
          echo "=== MLProject/mlruns Content ==="
          ls -R MLProject/mlruns || echo "mlruns folder NOT FOUND — training may have failed"

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns
          if-no-files-found: warn

      - name: Get Latest MLflow Model Path
        id: get_model
        run: |
          echo "Searching MLflow model folder..."
          model_path=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort | tail -n 1)

          if [ -z "$model_path" ]; then
            echo "Model folder not found!"
            exit 1
          fi

          echo "✔ Found model at: $model_path"
          echo "model_path=$model_path" >> $GITHUB_OUTPUT


      - name: Enable Docker
        run: |
          sudo systemctl start docker || true
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image Using MLflow
        run: |
          mlflow models build-docker \
            -m "${{ steps.get_model.outputs.model_path }}" \
            -n gempa-model

      - name: Tag Docker Image
        run: |
          docker tag gempa-model:latest ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
