name: MLflow CI

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.9.2 scikit-learn pandas docker

    - name: Run MLflow training script
      working-directory: MLProject
      run: python modelling.py

    - name: Get latest MLflow model artifact path
      id: get_model_path
      run: |
        MODEL_PATH=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort -r | head -n 1)
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV
        echo "Latest model: $MODEL_PATH"

    - name: Generate version tags
      id: versioning
      run: |
        if git describe --tags --abbrev=0 >/dev/null 2>&1; then
          VERSION=$(git describe --tags --abbrev=0)
        else
          VERSION="v0.0.0"
        fi
        CLEAN="${VERSION#v}"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN"
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "major=v$MAJOR" >> $GITHUB_ENV
        echo "minor=v$MAJOR.$MINOR" >> $GITHUB_ENV
        echo "patch=v$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
        echo "sha=sha-$SHORT_SHA" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Enable Docker SDK for MLflow
      run: |
        echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m $MODEL_PATH -n msml-model

    - name: Tag and push Docker images
      run: |
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:latest
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.major }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.minor }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.patch }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.sha }}

        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.major }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.minor }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.patch }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.sha }}
