name: MLflow CI

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # penting untuk ambil git tags

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas

    - name: Run MLflow training script
      working-directory: MLProject
      run: python modelling.py

    - name: Get latest MLflow model artifact path
      id: get_model_path
      run: |
        MODEL_PATH=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort -r | head -n 1)
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

    - name: Generate version tags
      id: versioning
      run: |
        # Try to get the latest git tag
        if git describe --tags --abbrev=0 >/dev/null 2>&1; then
          VERSION=$(git describe --tags --abbrev=0)
        else
          VERSION="v0.0.0"
        fi

        # Strip v prefix
        CLEAN="${VERSION#v}"

        IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN"

        SHORT_SHA=$(git rev-parse --short HEAD)

        echo "major=v$MAJOR" >> $GITHUB_ENV
        echo "minor=v$MAJOR.$MINOR" >> $GITHUB_ENV
        echo "patch=v$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
        echo "sha=sha-$SHORT_SHA" >> $GITHUB_ENV

        echo "VERSION=$VERSION"
        echo "Generated versions:"
        echo "  - latest"
        echo "  - v$MAJOR"
        echo "  - v$MAJOR.$MINOR"
        echo "  - v$MAJOR.$MINOR.$PATCH"
        echo "  - sha-$SHORT_SHA"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m $MODEL_PATH -t msml-model:latest

    - name: Tag and push Docker images
      run: |
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:latest
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.major }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.minor }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.patch }}
        docker tag msml-model:latest ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.sha }}

        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.major }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.minor }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.patch }}
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:${{ env.sha }}
