name: MLflow CI

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-log-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas

    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Commit and push MLflow artifacts
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add mlruns/*
        git commit -m 'Update MLflow model artifact'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest MLflow logged model path
      id: get_model_path
      run: |
        MODEL_PATH=$(find mlruns -type d -path "*/artifacts/model" | sort -r | head -n 1)
        echo "Latest MLflow model path: $MODEL_PATH"
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker -m $MODEL_PATH -n msml-model

    - name: Push Docker image to Docker Hub
      run: |
        docker tag msml-model:latest ${{ secrets.DOCKER_HUB_USERNAME }}/msml-model:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/msml-model:latest
