name: MLflow CI Training (Advance Level)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ""
          use-mamba: true

      - name: Install MLflow and dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      - name: Run MLflow Training Script
        working-directory: MLProject
        run: python modelling.py

      - name: Debug folder structure
        run: |
          echo "=== ROOT DIR ==="
          ls -R .
          echo "=== MLProject DIR ==="
          ls -R MLProject

      - name: DEBUG mlruns folder
        run: |
          echo "=== MLProject/mlruns Content ==="
          ls -R MLProject/mlruns || echo "mlruns folder NOT FOUND â€” training may have failed"

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns

      - name: Get Latest MLflow Model Path
        id: get_model
        run: |
          model_path=$(find MLProject/mlruns/0/models -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)
          echo "model_path=$model_path/artifacts" >> $GITHUB_OUTPUT

      - name: Enable Docker
        run: |
          sudo systemctl start docker || true
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image Using MLflow
        run: |
          mlflow models build-docker \
            -m ${{ steps.get_model.outputs.model_path }} \
            -n gempa-model:latest

      - name: Tag Docker Image
        run: |
          docker tag gempa-model:latest ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
