name: MLflow CI Training Advanced

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: ""
          use-mamba: true

      - name: Install MLflow and dependencies
        run: |
          pip install mlflow scikit-learn pandas seaborn matplotlib numpy

      - name: Run MLflow Project (training)
        run: |
          mlflow run MLProject -P data_path=katalog-gempa_preprocessing.csv --env-manager=local

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model_artifacts
          path: mlruns

      - name: Get Latest MLflow Model Path
        id: get_model
        run: |
          model_path=$(find mlruns -type d -path "*/artifacts/model" | sort | tail -n 1)
          echo "model_path=$model_path" >> $GITHUB_OUTPUT

      - name: Debug Model Path
        run: echo "MODEL PATH = ${{ steps.get_model.outputs.model_path }}"

      - name: Enable Docker
        run: |
          sudo systemctl start docker
          docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image Using MLflow
        run: |
          mlflow models build-docker \
            -m ${{ steps.get_model.outputs.model_path }}

      - name: List Docker Images
        run: docker images

      - name: Tag Docker Image Correctly
        run: |
          docker tag model ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
